# Inserts a blank line between shell prompts
add_newline = true

# # Replace the "â¯" symbol in the prompt with "âœ"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [memory_usage]
# format = "with$symbol [${ram} ${ram_pct}( | ${swap} ${swap_pct})]($style) "
# disabled = false
# threshold = -1
# symbol = " "
# style = "bold dimmed green"


[git_status]
ahead = "â‡¡ğŸğŸ’¨${count}"
diverged = "â‡•â‡¡ğŸ˜µ${ahead_count}â‡£${behind_count}"
behind = "â‡£ğŸ˜°${count}"
conflicted = "ğŸš©"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ’¥"

# [git_branch]
# symbol = "ğŸŒ± "

# [username]
# style_user = "blue bold"
# style_root = "red bold"
# format = "user: [$user]($style) "
# disabled = false
# show_always = true

# [directory]
# truncation_length = 7
# truncation_symbol = "â€¦/"

[python]
# symbol = "ğŸ‘¾ "
pyenv_version_name = true
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]


[time]
disabled = false
format = 'ğŸ•™[\[$time\]]($style) '
# time_format = "%T"
# utc_time_offset = "local"
# time_range = "09:00:00-18:00:00"

[status]
style = "bg:blue"
symbol = "ğŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
pipestatus = true


# [hg_branch]
# format = "on [ğŸŒ± $branch](bold purple)"
# truncation_length = 4
# truncation_symbol = ""
# disabled = false